version: "3.3"
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    hostname: nginx
    restart: always
    volumes:
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./configs/nginx/conf.d/example.com.conf:/etc/nginx/conf.d/example.com.conf
      - ${CODE_DIR}:/var/www
    ports:
      - "80:80"
    depends_on:
      - fpm
  fpm:
    build:
      context: ./build
      dockerfile: Dockerfile
    container_name: fpm
    hostname: fpm
    restart: always
    volumes:
      - ${CODE_DIR}:/var/www
      - ./configs:/configs
    entrypoint:
      - php-fpm
      - -R
      - -F
      - -y
      - /configs/fpm/php-fpm.conf
      - -c
      - /configs/fpm/php.ini
    depends_on:
      - db
  db:
    image: mysql:5.5.62
    container_name: db
    hostname: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: bmc
      MYSQL_DATABASE: bmc