version: "3.3"
services:
  nginx:
    build:
      context: ./
      dockerfile: build/Dockerfile-nginx
    container_name: nginx
    hostname: nginx
    restart: always
    volumes:
      - ./configs/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - fpm
  fpm:
    build:
      context: ./
      dockerfile: build/Dockerfile-fpm
    container_name: fpm
    hostname: fpm
    restart: always
    volumes:
      - ./configs:/configs
    entrypoint:
      - php-fpm
      - -R
      - -F
      - -y
      - /configs/fpm/php-fpm.conf
      - -c
      - /configs/fpm/php.ini
    depends_on:
      - db
  db:
    image: mysql:5.5.62
    container_name: db
    hostname: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bmc